### ISSUE TITLE
Documentação do perfil do usuário definido

### ISSUE THREAD

**Issue by ZenildaVieira** [Requisitos-de-Software/2023.2-Economia-DF#13]
# Documento: Definição do Perfil do Usuário
# Descrição
O perfil dos usuários do Programa Nota Legal é um componente essencial para o entendimento aprofundado das necessidades, comportamentos e motivações dos participantes. A documentação detalhada desse perfil, baseada nas informações obtidas através do grupo de foco e do questionário, é fundamental para orientar futuras estratégias e melhorias no programa.
Essa issue tem como finalidade a criação de um documento que consolide as duas técnicas escolhidas para definição do perfil do usuário (questionário e grupo de foco)  e apresente o perfil definido por essas técnicas.

# Tarefas
- [x] Reunir num documento markdown os resultados obtidos através das técnicas utilizadas.
- [x] Definir o perfil do usuário do programa Nota Legal, independente da plataforma.
- [x] Atualizar histórico de versões

# Observação

# Lembre-se de checar se o github pages possui:
- [x] O histórico de versão padronizado.
- [x] O(s) autor(es) e o(s) revisor(es) para cada artefato.
- [x] Referências bibliográficas e/ou bibliografia em todos os artefatos.
- [x] As tabelas e imagens  (se houver) possuem legenda e fonte e elas chamadas dentro dos texto.
- [x] Um texto fazendo uma introdução dos artefatos, por exemplo das “Ferramentas”.
- [x] A Especificação do Perfil do usuário possui informação de:
        • 1 - idade (criança, jovem, adulto, terceira idade etc.);
        • 2 - experiência (leigo/ novato, especialista);
        • 3 - atitudes (tecnófilos, tecnófobos); e
        • 4 - tarefas primárias (compra, venda)

**Comment by GZaranza** [comment]
Documento finalizado, preciso que alguem revise ele @gabrielrosa09 @ZenildaVieira
