### ISSUE TITLE
Perfil do Usuário - Questionário

### ISSUE THREAD

**Issue by ZenildaVieira** [Requisitos-de-Software/2023.2-Economia-DF#14]
# Perfil do Usuário - Questionário
## Descrição
O Programa Nota Legal é uma iniciativa que visa incentivar a emissão de notas fiscais legais por parte dos consumidores e cidadãos. Para melhor compreender o perfil dos usuários e suas necessidades, é essencial desenvolver um questionário estruturado que possa coletar informações relevantes sobre os participantes do programa, independentemente da plataforma que eles utilizam, sendo o site Nota Legal ou o aplicativo para chamado IOS Economia DF.

## Tarefas

- [x] Analisar exemplos de questionários utilizados em iniciativas semelhantes
- [x] Criar roteiro de perguntas
- [x] Montar um formulário e disponibilizá-lo

**Comment by GZaranza** [comment]
Questionário montado e colocamos para coletar respostas do dia 23/09 a 25/09
