### ISSUE TITLE
Priorização - In or Out

### ISSUE THREAD

**Issue by ZenildaVieira** [Requisitos-de-Software/2023.2-Economia-DF#19]
# Priorização - In or Out
## Descrição 
O objetivo desta issue é planejar e realizar uma sessão de priorização dos requisitos elicitados utilizando a técnica In or Out e documentar os resultados.

## Tarefas

- [x] Montar roteiro da técnica.
- [x] Criar um cronograma com data e local da reunião para realizar a técnica.
- [x] Participar da reunião - data e local agendado.
- [x] Documentar a reunião e priorzação dos requisitos.

## Observações:

- Mediador: Gabriel Zaranza
- Usuário/persona: Lucas Oliveira

**Comment by GZaranza** [comment]
Priorização realizada dia 30/09/2023 junto com o @LucasOliveiraDiasMarquesFerreira
