### ISSUE TITLE
Correção Entrega 01 - Termo de Uso

### ISSUE THREAD

**Issue by ZenildaVieira** [Requisitos-de-Software/2023.2-Economia-DF#25]
# Correção Entrega 01 - Termo de Uso

## Descrição
A partir da observação feita pelo monitor Natan:
_19 - Cópia do Termo de Uso, Direito de Uso ou Propriedade Intelectual do aplicativo permitindo o estudo na disciplina._
_obs7: não foi disponibilizado o termo de uso do aplicativo ou informado referência de onde foi retirado a informação de que aplicativos do governo podem ser utilizados para estudos._

**Corrigir a informação do termo de uso**

Prazo: 11 de outubro de 2023 - quarta-feira

## Tarefas

- [x] Corrigir a informação do termo de uso.
- [x] Atualizar histórico de versões.

# Observação

## Lembre-se de checar se o documento possui

- [x] O histórico de versão padronizado.
- [x] O(s) autor(es) e o(s) revisor(es) para cada artefato.
- [x] Referências bibliográficas e/ou bibliografia em todos os artefatos.
- [x] As tabelas e imagens  (se houver) possuem legenda e fonte e elas chamadas dentro dos texto.
- [ ] Um texto fazendo uma introdução dos artefatos.

**Comment by GZaranza** [comment]
Não consegui encontrar o termo de uso do aplicativo,  mandei email para o suporte deles perguntando sobre
