### ISSUE TITLE
Documentação - Tabelas de casos de uso

### ISSUE THREAD

**Issue by ZenildaVieira** [Requisitos-de-Software/2023.2-Economia-DF#42]
# Tabelas de casos de uso

## Descrição

Para cada caso de uso que consta no diagrama elaborado, criar uma tabela.

Prazo: 11 de outubro de 2003 - quarta-feira

## Tarefas

- [ ] Criação e documentação das tabelas em questão.
- [ ] Atualizar histórico de versões.

# Observação

## Lembre-se de checar se o github pages possui

- [ ] O histórico de versão padronizado.
- [ ] O(s) autor(es) e o(s) revisor(es) para cada artefato.
- [ ] Referências bibliográficas e/ou bibliografia em todos os artefatos.
- [ ] As tabelas e imagens  (se houver) possuem legenda e fonte e elas chamadas dentro dos texto.
- [ ] Um texto fazendo uma introdução dos artefatos, por exemplo das “Ferramentas”.

**Comment by GZaranza** [comment]
tabelas dos casos 1, 2 , 3 e 4 estão feitas. Falta colocar o numero das tabelas

**Comment by lucassouzs** [comment]
tabela dos casos 13, 14, 15 e 16 estão feitas. Falta colocar o numero das tabelas
