### ISSUE TITLE
Correção Entrega 02 - Documento Observação

### ISSUE THREAD

**Issue by ZenildaVieira** [Requisitos-de-Software/2023.2-Economia-DF#62]
# Correção Entrega 02 - Documento Observação

## Descrição

A partir da observação feita pelo monitor Natan:
19 - A participação do cliente e/ou persona na elicitação de requisitos?
A Observação foi realizada com um dos membros do grupo como o próprio usuário. Para melhores resultados e experiência, teria sido melhor com algum usuário que não fosse membro do grupo

Prazo: 25/10 - quarta

## Tarefas

- [x] Refazer ou não ? ? ? ? ? ? ? Vocês decidem.
- [x] Atualizar histórico de versões.

# Observação

## Lembre-se de checar se o github pages possui

- [x] O histórico de versão padronizado.
- [x] O(s) autor(es) e o(s) revisor(es) para cada artefato.
- [x] Referências bibliográficas e/ou bibliografia em todos os artefatos.
- [x] As tabelas e imagens  (se houver) possuem legenda e fonte e elas chamadas dentro dos texto.
- [x] Um texto fazendo uma introdução dos artefatos, por exemplo das “Ferramentas”.

**Comment by GZaranza** [comment]
Optamos por não refazer
