### ISSUE TITLE
Criação das perguntas do questionário - Perfil do Usuário

### ISSUE THREAD

**Issue by ZenildaVieira** [Requisitos-de-Software/2023.2-Economia-DF#9]
# Definição do Perfil do Usuário - Formulação do Questionário
# Descrição
Essa issue tem como objetivo formular as perguntas que serão feitas aos usuários por meio de um questionário para traçar o perfil dos usuários.

# Tarefas
- [ ] 
- [ ] 

# Observação

**Comment by GZaranza** [comment]
Perguntas e questionário feitos, começamos a coletar as respostas dia 23/09/23
